# Generated by Django 4.1 on 2022-08-20 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Linux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipadi', models.CharField(max_length=100)),
                ('kullaniciadi', models.CharField(max_length=100)),
                ('sifreadi', models.CharField(max_length=100)),
                ('portadi', models.CharField(max_length=100)),
                ('komutadi', models.CharField(max_length=200)),
                ('dateadi', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
