# Generated by Django 4.1 on 2022-09-17 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linux', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linux',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='linux',
            name='dateadi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='olusturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='linux',
            name='ipadi',
            field=models.GenericIPAddressField(verbose_name='Ip adresi'),
        ),
        migrations.AlterField(
            model_name='linux',
            name='komutadi',
            field=models.CharField(max_length=200, verbose_name='Calistirilmasi istenen komut'),
        ),
        migrations.AlterField(
            model_name='linux',
            name='kullaniciadi',
            field=models.CharField(max_length=100, verbose_name='User Adi'),
        ),
        migrations.AlterField(
            model_name='linux',
            name='portadi',
            field=models.CharField(max_length=100, verbose_name='Port Numarasi'),
        ),
        migrations.AlterField(
            model_name='linux',
            name='sifreadi',
            field=models.CharField(max_length=100, verbose_name='Sifre'),
        ),
        migrations.CreateModel(
            name='Pardus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komut', models.CharField(max_length=10000, verbose_name='komut')),
                ('kullanicilarinAdi', models.CharField(max_length=10000, verbose_name='kullanicilarinAdi')),
                ('hostname', models.CharField(max_length=10000, verbose_name='hostname')),
                ('ip', models.CharField(max_length=10000, verbose_name='ip')),
                ('toplamRam', models.CharField(max_length=10000, verbose_name='toplamRam')),
                ('toplamBosRam', models.CharField(max_length=10000, verbose_name='toplamBosRam')),
                ('diskToplam', models.CharField(max_length=10000, verbose_name='diskToplam')),
                ('cPU', models.CharField(max_length=10000, verbose_name='cPU')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Admin')),
            ],
        ),
    ]
